// Auto-generated by upload-badges-pinata.js
// Badge ID -> IPFS metadata URI
export const BADGE_TOKEN_URIS: Record<string, string> = {
  'first-game': 'ipfs://bafkreiczx6oerb3bnjetzgr2bwgziuuoa373gpglesvxp23dmulm7ndnwi',
  'five-games': 'ipfs://bafkreiekkewdloapyri4nrqllr4hkitpgm2h5gylro4fxsaa3tfkfofaia',
  'ten-games': 'ipfs://bafkreidk5dqbpjvoobpjl4fktsqaync7t22un4o4qik4djytklscrygot4',
  'twenty-five-games': 'ipfs://bafkreihagsq23wum6bf6s4ma2rvk5rmcwgthcarqv2lcikhtjpzqibgvai',
  'fifty-games': 'ipfs://bafkreih5mgafq3weriokfuicjryt53nmdsrcy57j7yr4q2r22lovvnzhwy',
  'xp-100': 'ipfs://bafkreigft4h5b2jak253xtcsb4aa5j4rtuvrlwyptd3cclob6ci4qison4',
  'xp-500': 'ipfs://bafkreignzjhb44q5zfuyi5wpcduw423vpnbv5jimt3ih2ilea244dzsdtq',
  'xp-1000': 'ipfs://bafkreiesoagexy77vtlucddtoih7gxdkb3mtwjk6ic4lrw3xmnrqvharum',
  'flappy-10': 'ipfs://bafkreigp4gse3gvp4mmtjhmb2swytack2qu6z43l4dmou6iiotismrirsu',
  'flappy-50': 'ipfs://bafkreidqqnei2kiqvos5gozemuoqoyu3gioc6oyvu42hwyjzgflmizasty',
  'neon-1000': 'ipfs://bafkreiai3j5z6mi2mdexb4g6xmvcbur6tg3ipd6dewmvhnqj764mndqn5m',
  'neon-10000': 'ipfs://bafkreibdoulivh3ylixxms3yf3l2y265ujt2kqqvppzu5qzcuwrkupco7y',
  'tilenova-500': 'ipfs://bafkreigwmlhxsmvuxehhjcmwzdznnhry2xtn5kxkwj2e3i3dluvbfdklfy',
  'tilenova-5000': 'ipfs://bafkreidhsggibnrx7gn24npx77fboo2nshxt6bbb5uw7rqva2oby7beiuy',
  'all-rounder': 'ipfs://bafkreie5qsh64q3rkcn26smu6e3e6xemht3xt5avn4fq23cvqejwcu4jyy',
};

/**
 * Get the token URI for a badge.
 * Returns IPFS URI if available, otherwise generates base64 metadata.
 */
export function getBadgeTokenURI(badgeId: string, badgeName: string, badgeDescription: string, badgeTier: string): string {
  if (BADGE_TOKEN_URIS[badgeId]) {
    return BADGE_TOKEN_URIS[badgeId];
  }

  const appUrl = process.env.NEXT_PUBLIC_APP_URL || 'https://arcade-web-teal.vercel.app';
  const metadata = {
    name: badgeName,
    description: badgeDescription,
    image: `${appUrl}/badges/${badgeId}.svg`,
    external_url: `${appUrl}/dashboard`,
    attributes: [
      { trait_type: 'Tier', value: badgeTier.charAt(0).toUpperCase() + badgeTier.slice(1) },
      { trait_type: 'Badge ID', value: badgeId },
    ],
    properties: { badge_id: badgeId, platform: 'Ginix Arcade', chain: 'Avalanche Fuji' },
  };
  return `data:application/json;base64,${Buffer.from(JSON.stringify(metadata)).toString('base64')}`;
}
